apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: web
  name: nginx-deploy
spec:
  replicas: 2
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      volumes:
      - name: www
        persistentVolumeClaim:
          claimName: dyna-nfs
      containers:
      - image: nginx:1.19
        name: nginx
        volumeMounts:
        - name: www
          mountPath: /usr/share/nginx/html
