apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-hostpath-4g
  labels:
    type: local
spec:
  storageClassName: 4g
  capacity:
    storage: 4Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/kube"
