apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-nfs
  labels:
    type: local
spec:
  storageClassName: nfs
  capacity:
    storage: 8Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: 172.42.42.50
    path: "/nfs/kubedata"
