apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: apache-ludo
  namespace: ludo
spec:
  storageClassName: nfs-storage
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
