apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: apache
  namespace: monitoring
spec:
  storageClassName: nfs-storage
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
