apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: ludo
  annotations:
    kubernetes.io/change-cause: "update 1.14 to 1.19"
  labels:
    app: web
  name: nginx
spec:
  replicas: 6
  selector:
    matchLabels:
      app: web
  strategy:
    type: Recreate
  minReadySeconds: 5
  revisionHistoryLimit: 10
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
      - image: nginx:1.19
        name: nginx
